add cd pipeline

diff --git a/.github/workflows/api-test.yaml b/.github/workflows/api-test.yaml
--- a/.github/workflows/api-test.yaml
+++ b/.github/workflows/api-test.yaml
@@ -1,4 +1,4 @@
-name: Newman Automated API Tests
+name: Newman Automated API Tests CI/CD
 
 # Trigger the workflow on push or pull request
 on:
@@ -7,12 +7,16 @@ on:
   pull_request:
     branches: ['main', 'master']
 
-# Set the job to run on Ubuntu
+# Permission for GitHub Actions to write to GitHub Pages
+permissions:
+  contents: read
+  pages: write
+  id-token: write
 
+# Set the job to run on Ubuntu
 jobs:
   test-api:
     runs-on: ubuntu-latest
-
     steps:
       # Checkout repo
       - name: Checkout Repository
@@ -30,15 +34,41 @@ jobs:
           npm install -g newman
           npm install -g newman-reporter-htmlextra
 
+      # Create folder 'public' for the report
+      - name: Create Report Directory
+        run: mkdir -p public
+
       # Run the API tests using Newman and generate an HTML report
       - name: Run API Tests and Generate Report
-        run: newman run "Simple Grocery Store API.postman_collection.json" -r cli,htmlextra --reporter-htmlextra-export newman-report.html
+        id: run-tests
+        # Run Newman with the specified collection and generate an HTML report in the 'public' folder
+        run: newman run "Simple Grocery Store API.postman_collection.json" -r cli,htmlextra --reporter-htmlextra-export public/index.html
         # Continue even if there are test failures
         continue-on-error: true
 
-      # Upload the generated HTML report as an artifact for later review
-      - name: Upload HTML Report as Artifact
-        uses: actions/upload-artifact@v4
+      # Packaging the 'public' folder into a custom artifact for GitHub Pages
+      - name: Upload artifact for GitHub Pages
+        uses: actions/upload-pages-artifact@v3
         with:
-          name: newman-api-report
-          path: newman-report.html
+          path: ./public
+
+      - name: Check Test Status
+        if: steps.run-tests.outcome == 'failure'
+        run: |
+          echo "Tests failed, marking workflow as failed after report upload."
+          exit 1
+
+  deploy-to-pages:
+    # This job will only run if the 'test-api' job completes successfully
+    needs: test-api
+    runs-on: ubuntu-latest
+
+    # Set up the environment for GitHub Pages deployment
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+
+    steps:
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v4
